apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gitrepo-flex-ds
spec:
  template:
    metadata:
      name:  gitrepo-flex-ds
      labels:
        app:  gitrepo-flex-ds
    spec:
      initContainers:
        # TODO Change to your container registry.
        - image: "k8s-flexvol-gitrepo:latest"
          imagePullPolicy: Always
          name: flex-deploy
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-mount
          env:
          - name: VENDOR
            valueFrom:
              configMapKeyRef:
                name: gitrepo-flex-ds
                key: vendor
          - name: DRIVER
            valueFrom:
              configMapKeyRef:
                name: gitrepo-flex-ds
                key: driver
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: gitrepo-deploy-parameters
                key: debug
          - name: GIT_VERSION
            valueFrom:
              configMapKeyRef:
                name: gitrepo-deploy-parameters
                key: gitVersion
          - name: JQ_VERSION
            valueFrom:
              configMapKeyRef:
                name: gitrepo-deploy-parameters
                key: jqVersion
          - name: HOST_TARGET
            valueFrom:
              configMapKeyRef:
                name: gitrepo-deploy-parameters
                key: hostTarget

      containers:
        - image: "busybox:latest"
          imagePullPolicy: IfNotPresent
          name: sleeper
          command:
          - sleep
          args:
          - 365d
        
      volumes:
        - name: flexvolume-mount
          hostPath:
            # TODO Change to the Flexvolume plugin directory of your cluster.
            path: $(pluginDir)
