apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: k8s-gitrepo-vol

resources:
- daemonset.yaml
- configMap.yaml

configMapGenerator:
- name: gitrepo-deploy-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: pluginDir
  objref:
    kind: ConfigMap
    name: gitrepo-deploy-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.pluginDir

images:
- name: k8s-flexvol-gitrepo
  newName: piersharding/k8s-flexvol-gitrepo
  newTag: latest

configurations:
- params.yaml
